name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Set branch name
        run: echo >>$GITHUB_ENV BRANCH_NAME=${GITHUB_REF#refs/heads/}
      - name: Output branch name
        run: echo ${BRANCH_NAME}
      - run: npm install
      - run: npm run lint:nofix
      - run: npm run build
      - run: npm run test
      - name: Generate coverage
        run: npm run coverage
      - name: Publish
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TEST_NPM_TOKEN}}
