name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # node_version: [12.x]
        # os: [ubuntu-latest]
        node_version: 12.x
        os: ubuntu-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.node_version }}-nodemodules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node_version }}-nodemodules-
      - name: Install Dep
        run: npm install
      - run: npm run lint:nofix
      - run: npm run build
      - run: npm run test
      - name: Generate coverage
        if: matrix.node_version == '12.x' && matrix.os == 'ubuntu-latest'
        run: npm run coverage
