name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run lint:nofix
      - run: npm run build
      - run: npm run test
      - name: Generate coverage
        run: npm run coverage
